### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/connector-dev#1]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] connector_base_backend_link
- [ ] connector_dev
- [ ] connector_dev_delete_job
- [ ] connector_dev_traceback
- [ ] connector_job_tree
- [ ] connector_magento_backend_link
